project_name: sap-devs

version: 2

builds:
  - main: .
    binary: sap-devs
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -X github.tools.sap/developer-relations/sap-devs-cli/cmd.Version={{ .Version }}

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: false
    files:
      - none*

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  sort: asc
