# This file was generated by GoReleaser. DO NOT EDIT.
cask "sap-devs" do
  version "0.0.8"

  on_macos do
    on_intel do
      sha256 "700e0122ad5957497707f83e0654010723222a93d221afa8994db59840e39f8c"
      url "https://github.com/SAP-samples/sap-devs-cli/releases/download/v#{version}/sap-devs_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0ac41b5b9e172d311139c048d69cef6afc1c025cc2a9af704ad4515e37e013c9"
      url "https://github.com/SAP-samples/sap-devs-cli/releases/download/v#{version}/sap-devs_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "18f04f2662435cfe8faa3b98e6d1d567457ffa70a7e98240a7abfd8f1a90070d"
      url "https://github.com/SAP-samples/sap-devs-cli/releases/download/v#{version}/sap-devs_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ba980791bbb40242f0a325595248a2e2f9055b37209d36f0ef4960fb9c262674"
      url "https://github.com/SAP-samples/sap-devs-cli/releases/download/v#{version}/sap-devs_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sap-devs"
  desc "SAP developer context CLI — inject SAP knowledge into AI coding tools"
  homepage "https://github.com/SAP-samples/sap-devs-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sap-devs"

  # No zap stanza required

end
