# This file was generated by GoReleaser. DO NOT EDIT.
cask "sap-devs" do
  version "0.0.5"

  on_macos do
    on_intel do
      sha256 "de0985f9e42cac08c505b4a9b3ea5a18ecac281a1120ad40571c11603f75e221"
      url "https://github.com/SAP-samples/sap-devs-cli/releases/download/v#{version}/sap-devs_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "34a99a053d2970d74918ce5f0cd9c6661b8a4a9fdf8c5830a10b28d686ba49f0"
      url "https://github.com/SAP-samples/sap-devs-cli/releases/download/v#{version}/sap-devs_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "77a445becf4b014bd0a992b60a7d140d5c2b5653a6f85f9d682f2d7c340ecae9"
      url "https://github.com/SAP-samples/sap-devs-cli/releases/download/v#{version}/sap-devs_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1bfcc43b687390e6762f1037cf1b6872ae6b2ef3d154db9443082e23295f805f"
      url "https://github.com/SAP-samples/sap-devs-cli/releases/download/v#{version}/sap-devs_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sap-devs"
  desc "SAP developer context CLI — inject SAP knowledge into AI coding tools"
  homepage "https://github.com/SAP-samples/sap-devs-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sap-devs"

  # No zap stanza required

end
