# This file was generated by GoReleaser. DO NOT EDIT.
cask "sap-devs" do
  version "0.0.7"

  on_macos do
    on_intel do
      sha256 "7519c4021b80d29f4b7d885d0adbc3959599a4621f7efd1e200ff16d7a0a2385"
      url "https://github.com/SAP-samples/sap-devs-cli/releases/download/v#{version}/sap-devs_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6f518976da7da44c972effb916763e4dadb1b2a692f931f42ffde5f56b07ef90"
      url "https://github.com/SAP-samples/sap-devs-cli/releases/download/v#{version}/sap-devs_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a03a49674b87952d10a796a2e65bc105bf8a65ea354a1931994e433f0f5c4d15"
      url "https://github.com/SAP-samples/sap-devs-cli/releases/download/v#{version}/sap-devs_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cac6180eda88b7d6b8a6e145ee16d7775d9808473575e03ed5c2ef1198f9638f"
      url "https://github.com/SAP-samples/sap-devs-cli/releases/download/v#{version}/sap-devs_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sap-devs"
  desc "SAP developer context CLI — inject SAP knowledge into AI coding tools"
  homepage "https://github.com/SAP-samples/sap-devs-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sap-devs"

  # No zap stanza required

end
